# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Workshop on Robot Execution Failures and Failure Management Strategies"
email: "aleksandar.mitrevski@h-brs.de"
description: "ICRA 2023 Workshop on Robot Execution Failures and Failure Management Strategies"
baseurl: "/icra2023"
url: "https://robot-failures.github.io"
permalink: "/news/:title"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Autonomous Systems Group at Hochschule Bonn-Rhein-Sieg"
organizerEmail: "aleksandar.mitrevski@h-brs.de"
organizerLink: "https://mas.b-it-center.de"

# Head
metaKeywords: "event, robot-failures, workshop, icra2023"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/description/", text: "Description"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/call-for-papers/", text: "Call for papers"}
 - {permalink: "/organisers/", text: "Organisers"}
 - {permalink: "/news/", text: "News"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Workshop on Robot Execution Failures and Failure Management Strategies"
eventDate: "Workshop at ICRA 2023 (Proposal)"

# Latest News Block
latestNewsTitle: "Latest news"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Join the discussion at"
twitterHashTag: "robot_failures_icra"

# Partners Block
organizersTitle: "Organisers"

# Footer
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.icra2023.org", text: "ICRA 2023"}
   - {link: "https://www.ieee-ras.org/about-ras/diversity-page/ieee-ras-code-of-conduct", text: "IEEE RAS Code of Conduct"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:aleksandar.mitrevski@h-brs.de", text: "aleksandar.mitrevski@h-brs.de"}

blogTitle: "Latest news"
blogCommentsEnabled: false
