# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Workshop on Robot Execution Failures and Failure Management Strategies"
email: "robot-failures@h-brs.de"
description: "ICRA 2023 Workshop on Robot Execution Failures and Failure Management Strategies"
baseurl: "/icra2023"
url: "https://robot-failures.github.io"
permalink: "/blog/:title"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Autonomous Systems Group at Hochschule Bonn-Rhein-Sieg"
organizerEmail: "robot-failures@h-brs.de"
organizerLink: "https://mas.b-it-center.de"

# Head
metaKeywords: "event, robot-failures, workshop, icra2023"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/description/", text: "Description"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/call-for-papers/", text: "Call for papers"}
 - {permalink: "/organisers/", text: "Organisers"}
 - {permalink: "/news/", text: "News"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Workshop on Robot Execution Failures and Failure Management Strategies"
eventDate: "Workshop at ICRA 2023 (Proposal)"

# About Block
aboutTitle: "About the Workshop"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Latest News Block
latestNewsTitle: "Latest news"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Join the discussion at"
twitterHashTag: "robot_failures_icra"

# Partners Block
organizersTitle: "Organisers"

# Footer
footerBlocks:
 -
  title: "Links"
 -
  title: "Contacts"
  links:
   - {link: "mailto:robot-failures@h-brs.de", text: "robot-failures@h-brs.de"}
 -
  title: "FAQ"
